shutdown_costmaps: false

controller_frequency: 10.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

# Local planner
# base_local_planner: dwa_local_planner/DWAPlannerROS
base_local_planner: p09_llc_nd_local_planner/LLCNDLocalPlanner
# ALTERNATIVES: dwa_local_planner/DWAPlannerROS, base_local_planner/TrajectoryPlannerROS

# Global planner
base_global_planner: global_planner/GlobalPlanner
# base_global_planner: carrot_planner/CarrotPlanner
# ALTERNATIVES: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner, navfn/NavfnROS
