LLCNDLocalPlanner:
  distance_robot_bounds: 0.225
  robot_radius_nd: 0.5
  distance_goal_factor: 1.0
  max_linear_velocity: 0.5
  max_rotational_velocity: 1.57
  max_sensor_distance: 3.0
  security_distance: 1
  num_sectors: 144
  wide_area_angle: 90